name: Build all emu variants (macos)

on:
  workflow_call:
    # needed since it allows this to become a reusable workflow
  workflow_dispatch:
    # allows manual trigger

permissions:
  contents: write

jobs:
  deps:
    name: Restore or build deps
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/emu-deps-macos.yml

  emu-regular-x64-release:
    name: Regular x64 (release)
    needs: [ deps ]
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/emu-build-variant-macos.yml
    with:
      emu-variant: regular
      debug: false

  emu-regular-x64-debug:
    name: Regular x64 (debug)
    needs: [ deps ]
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/emu-build-variant-macos.yml
    with:
      emu-variant: regular
      debug: true

  emu-exp-x64-release:
    name: Experimental x64 (release)
    needs: [ deps ]
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/emu-build-variant-macos.yml
    with:
      emu-variant: exp
      debug: false

  emu-exp-x64-debug:
    name: Experimental x64 (debug)
    needs: [ deps ]
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/emu-build-variant-macos.yml
    with:
      emu-variant: exp
      debug: true

  tools-x64-release:
    name: Tools x64 (release)
    needs: [ deps ]
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/emu-build-variant-macos.yml
    with:
      emu-variant: tools
      debug: false

  tools-x64-debug:
    name: Tools x64 (debug)
    needs: [ deps ]
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/emu-build-variant-macos.yml
    with:
      emu-variant: tools
      debug: true
