name: Emu pull request (Windows)

on:
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - '**/*.md'
      - 'dev.notes/**'
      - 'post_build/**'
      - 'z_original_repo_files/**'
      - 'sdk/*.txt'
      - 'LICENSE'
      # tools
      - 'tools/generate_emu_config/**'
      - 'tools/migrate_gse/**'
      - 'tools/steamclient_loader/linux/**'

permissions:
  contents: write

jobs:
  emu-win-all:
    name: Emu win all
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/build-emu-all-win.yml
